//! Shared execution and result types for named trade studies and Monte Carlo studies.
//!
//! Studies execute sequentially because EDS target files currently share a workspace. A caller
//! must give each concurrently running study a separate EDS workspace.

use std::collections::{BTreeMap, HashSet};
use std::time::{Duration, Instant};

use anyhow::{Result, bail};
use rand::{Rng, RngCore, SeedableRng};
use rand_chacha::ChaCha8Rng;
use rand_distr::{Distribution, LogNormal, Normal, Triangular, Uniform};
use serde::{Deserialize, Serialize};
use tokio_util::sync::CancellationToken;

use crate::{EdsPatch, SedaroSimulator, SimulationResult};

/// Identifies an EDS field whose value can vary between study cases.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct EdsPatchTarget {
    pub agent_id: String,
    pub engine: String,
    pub field: String,
    pub type_: String,
}

impl EdsPatchTarget {
    /// Creates a reusable target for EDS patches generated by a study.
    pub fn new(agent_id: &str, engine: &str, field: &str, type_: &str) -> Self {
        Self {
            agent_id: agent_id.to_string(),
            engine: engine.to_string(),
            field: field.to_string(),
            type_: type_.to_string(),
        }
    }

    /// Creates a patch for this target from a serialized EDS value.
    pub fn patch(&self, value: impl ToString) -> EdsPatch {
        EdsPatch::new(
            &self.agent_id,
            &self.engine,
            &self.field,
            &self.type_,
            &value.to_string(),
        )
    }
}

/// One named simulation case and the parameters that produced it.
#[derive(Clone, Debug)]
pub struct StudyCase {
    pub id: String,
    pub parameters: BTreeMap<String, f64>,
    pub patches: Vec<EdsPatch>,
    pub seed: Option<u64>,
}

impl StudyCase {
    /// Creates an empty named study case.
    pub fn new(id: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            parameters: BTreeMap::new(),
            patches: Vec::new(),
            seed: None,
        }
    }

    /// Adds an EDS patch applied only to this case.
    pub fn patch(mut self, patch: EdsPatch) -> Self {
        self.patches.push(patch);
        self
    }

    /// Adds several EDS patches applied only to this case.
    pub fn patch_multi(mut self, patches: Vec<EdsPatch>) -> Self {
        self.patches.extend(patches);
        self
    }

    /// Records a numeric parameter so it remains associated with the result.
    pub fn parameter(mut self, name: impl Into<String>, value: f64) -> Self {
        self.parameters.insert(name.into(), value);
        self
    }
}

/// A failure to launch a simulation or collect its output.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StudyRunFailure {
    pub message: String,
}

/// The process-level outcome of one study case.
#[derive(Clone, Debug)]
pub enum StudyRunOutcome {
    Completed(SimulationResult),
    Failed(StudyRunFailure),
    Cancelled,
}

/// A study case paired with its process outcome and elapsed wall-clock time.
#[derive(Clone, Debug)]
pub struct StudyRunResult {
    pub case: StudyCase,
    pub outcome: StudyRunOutcome,
    pub elapsed: Duration,
}

impl StudyRunResult {
    /// Returns the simulation result when the process launched and output collection completed.
    pub fn simulation_result(&self) -> Option<&SimulationResult> {
        match &self.outcome {
            StudyRunOutcome::Completed(result) => Some(result),
            StudyRunOutcome::Failed(_) | StudyRunOutcome::Cancelled => None,
        }
    }

    /// Reports whether the simulation completed with a successful exit status.
    pub fn succeeded(&self) -> bool {
        self.simulation_result()
            .is_some_and(|result| result.success)
    }

    /// Reports whether cancellation interrupted this run after it started.
    pub fn cancelled(&self) -> bool {
        matches!(self.outcome, StudyRunOutcome::Cancelled)
    }
}

/// Explains why a study stopped scheduling cases.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StudyTermination {
    Completed,
    Cancelled,
}

/// Ordered results and termination metadata for a study.
#[derive(Clone, Debug)]
pub struct StudyResult {
    pub planned_runs: usize,
    pub runs: Vec<StudyRunResult>,
    pub termination: StudyTermination,
    pub seed: Option<u64>,
}

impl StudyResult {
    /// Finds a run by its case identifier.
    pub fn get(&self, id: &str) -> Option<&StudyRunResult> {
        self.runs.iter().find(|run| run.case.id == id)
    }

    /// Iterates over runs whose simulations exited successfully.
    pub fn successful_runs(&self) -> impl Iterator<Item = &StudyRunResult> {
        self.runs.iter().filter(|run| run.succeeded())
    }

    /// Iterates over infrastructure failures and simulations with unsuccessful exits.
    pub fn failed_runs(&self) -> impl Iterator<Item = &StudyRunResult> {
        self.runs.iter().filter(|run| match &run.outcome {
            StudyRunOutcome::Completed(result) => !result.success,
            StudyRunOutcome::Failed(_) => true,
            StudyRunOutcome::Cancelled => false,
        })
    }

    /// Returns the number of planned cases that were not started.
    pub fn remaining_runs(&self) -> usize {
        self.planned_runs.saturating_sub(self.runs.len())
    }
}

/// Runs an explicit, ordered set of named simulation cases.
#[derive(Clone, Debug)]
pub struct TradeStudy {
    simulator: SedaroSimulator,
    duration_days: f64,
    cases: Vec<StudyCase>,
}

impl TradeStudy {
    /// Creates a named-case study from a base simulator configuration.
    pub fn new(simulator: SedaroSimulator, duration_days: f64) -> Self {
        Self {
            simulator,
            duration_days,
            cases: Vec::new(),
        }
    }

    /// Appends a case while preserving insertion order.
    pub fn case(mut self, case: StudyCase) -> Self {
        self.cases.push(case);
        self
    }

    /// Runs all cases sequentially.
    pub async fn run(&self) -> Result<StudyResult> {
        let cancellation = CancellationToken::new();
        self.run_with_cancellation(&cancellation).await
    }

    /// Runs cases sequentially until all finish or cancellation is requested.
    pub async fn run_with_cancellation(
        &self,
        cancellation: &CancellationToken,
    ) -> Result<StudyResult> {
        run_cases(
            &self.simulator,
            self.duration_days,
            self.cases.clone(),
            cancellation,
            None,
        )
        .await
    }
}

/// A supported probability distribution for one independent Monte Carlo input.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum ProbabilityDistribution {
    Normal { mean: f64, std_dev: f64 },
    Uniform { low: f64, high: f64 },
    LogNormal { mean: f64, std_dev: f64 },
    Triangular { low: f64, high: f64, mode: f64 },
    Discrete { values: Vec<f64> },
}

impl ProbabilityDistribution {
    /// Validates distribution parameters before a study starts.
    fn validate(&self) -> Result<()> {
        match self {
            Self::Normal { mean, std_dev } | Self::LogNormal { mean, std_dev } => {
                if !mean.is_finite() || !std_dev.is_finite() || *std_dev <= 0.0 {
                    bail!("distribution mean must be finite and std_dev must be finite and > 0");
                }
            }
            Self::Uniform { low, high } => {
                if !low.is_finite() || !high.is_finite() || low >= high {
                    bail!("uniform bounds must be finite and low must be less than high");
                }
            }
            Self::Triangular { low, high, mode } => {
                if !low.is_finite()
                    || !high.is_finite()
                    || !mode.is_finite()
                    || low >= high
                    || mode < low
                    || mode > high
                {
                    bail!(
                        "triangular bounds and mode must be finite with low < high and low <= mode <= high"
                    );
                }
            }
            Self::Discrete { values } => {
                if values.is_empty() || values.iter().any(|value| !value.is_finite()) {
                    bail!("discrete distribution values must be non-empty and finite");
                }
            }
        }
        Ok(())
    }

    /// Draws one value from the distribution using the supplied RNG.
    ///
    /// Exposing sampling lets callers build domain-specific case values, such as
    /// perturbations around a baseline supplied by live telemetry, while using
    /// the same validated distributions as `MonteCarloStudy`.
    pub fn sample<R: Rng + ?Sized>(&self, rng: &mut R) -> Result<f64> {
        self.validate()?;
        Ok(match self {
            Self::Normal { mean, std_dev } => Normal::new(*mean, *std_dev)?.sample(rng),
            Self::Uniform { low, high } => Uniform::new(*low, *high)?.sample(rng),
            Self::LogNormal { mean, std_dev } => LogNormal::new(*mean, *std_dev)?.sample(rng),
            Self::Triangular { low, high, mode } => {
                Triangular::new(*low, *high, *mode)?.sample(rng)
            }
            Self::Discrete { values } => values[rng.random_range(0..values.len())],
        })
    }
}

/// Connects a named Monte Carlo input distribution to an EDS patch target.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonteCarloParameter {
    pub name: String,
    pub target: EdsPatchTarget,
    pub distribution: ProbabilityDistribution,
}

impl MonteCarloParameter {
    /// Creates an independently sampled Monte Carlo input.
    pub fn new(
        name: impl Into<String>,
        target: EdsPatchTarget,
        distribution: ProbabilityDistribution,
    ) -> Self {
        Self {
            name: name.into(),
            target,
            distribution,
        }
    }
}

/// Generates reproducible simulation cases from independent input distributions.
#[derive(Clone, Debug)]
pub struct MonteCarloStudy {
    simulator: SedaroSimulator,
    duration_days: f64,
    samples: usize,
    seed: u64,
    parameters: Vec<MonteCarloParameter>,
}

impl MonteCarloStudy {
    /// Creates a Monte Carlo study with no samples or parameters configured.
    pub fn new(simulator: SedaroSimulator, duration_days: f64) -> Self {
        Self {
            simulator,
            duration_days,
            samples: 0,
            seed: 0,
            parameters: Vec::new(),
        }
    }

    /// Sets the number of simulation cases to generate.
    pub fn samples(mut self, samples: usize) -> Self {
        self.samples = samples;
        self
    }

    /// Sets the deterministic seed used to derive each case seed.
    pub fn seed(mut self, seed: u64) -> Self {
        self.seed = seed;
        self
    }

    /// Appends one independently sampled parameter.
    pub fn parameter(mut self, parameter: MonteCarloParameter) -> Self {
        self.parameters.push(parameter);
        self
    }

    /// Generates and runs all Monte Carlo cases sequentially.
    pub async fn run(&self) -> Result<StudyResult> {
        let cancellation = CancellationToken::new();
        self.run_with_cancellation(&cancellation).await
    }

    /// Generates cases and runs them until all finish or cancellation is requested.
    pub async fn run_with_cancellation(
        &self,
        cancellation: &CancellationToken,
    ) -> Result<StudyResult> {
        run_cases(
            &self.simulator,
            self.duration_days,
            self.generate_cases()?,
            cancellation,
            Some(self.seed),
        )
        .await
    }

    /// Validates the design and deterministically generates sampled study cases without running EDS.
    pub fn generate_cases(&self) -> Result<Vec<StudyCase>> {
        if self.samples == 0 {
            bail!("Monte Carlo study requires at least one sample");
        }
        if self.parameters.is_empty() {
            bail!("Monte Carlo study requires at least one parameter");
        }

        let mut names = HashSet::new();
        for parameter in &self.parameters {
            if parameter.name.trim().is_empty() {
                bail!("Monte Carlo parameter names must not be empty");
            }
            if !names.insert(parameter.name.as_str()) {
                bail!("duplicate Monte Carlo parameter '{}'", parameter.name);
            }
            parameter.distribution.validate()?;
        }

        let mut seed_rng = ChaCha8Rng::seed_from_u64(self.seed);
        let mut cases = Vec::with_capacity(self.samples);
        for index in 0..self.samples {
            let case_seed = seed_rng.next_u64();
            let mut case_rng = ChaCha8Rng::seed_from_u64(case_seed);
            let mut case = StudyCase::new(format!("sample-{index:04}"));
            case.seed = Some(case_seed);

            for parameter in &self.parameters {
                let value = parameter.distribution.sample(&mut case_rng)?;
                if !value.is_finite() {
                    bail!(
                        "Monte Carlo parameter '{}' generated a non-finite value for case '{}'",
                        parameter.name,
                        case.id
                    );
                }
                case.parameters.insert(parameter.name.clone(), value);
                case.patches.push(parameter.target.patch(value));
            }
            cases.push(case);
        }
        Ok(cases)
    }
}

/// Validates and executes cases using a common sequential study policy.
async fn run_cases(
    simulator: &SedaroSimulator,
    duration_days: f64,
    cases: Vec<StudyCase>,
    cancellation: &CancellationToken,
    seed: Option<u64>,
) -> Result<StudyResult> {
    if !duration_days.is_finite() || duration_days <= 0.0 {
        bail!("study duration_days must be finite and > 0");
    }
    if cases.is_empty() {
        bail!("study requires at least one case");
    }

    let mut ids = HashSet::new();
    for case in &cases {
        if case.id.trim().is_empty() {
            bail!("study case IDs must not be empty");
        }
        if !ids.insert(case.id.as_str()) {
            bail!("duplicate study case ID '{}'", case.id);
        }
    }

    let planned_runs = cases.len();
    let mut runs = Vec::with_capacity(planned_runs);
    let mut termination = StudyTermination::Completed;

    for case in cases {
        if cancellation.is_cancelled() {
            termination = StudyTermination::Cancelled;
            break;
        }

        let configured_simulator = simulator.clone().patch_multi(case.patches.clone());
        let started = Instant::now();
        let run_result = tokio::select! {
            biased;
            _ = cancellation.cancelled() => None,
            result = configured_simulator.run_collect(duration_days) => Some(result),
        };

        let outcome = match run_result {
            Some(Ok(result)) => StudyRunOutcome::Completed(result),
            Some(Err(error)) => StudyRunOutcome::Failed(StudyRunFailure {
                message: format!("{error:#}"),
            }),
            None => StudyRunOutcome::Cancelled,
        };
        runs.push(StudyRunResult {
            case,
            outcome,
            elapsed: started.elapsed(),
        });
        if runs.last().is_some_and(StudyRunResult::cancelled) {
            termination = StudyTermination::Cancelled;
            break;
        }
    }

    Ok(StudyResult {
        planned_runs,
        runs,
        termination,
        seed,
    })
}

#[cfg(test)]
mod tests {
    use std::os::unix::fs::PermissionsExt;
    use std::path::PathBuf;
    use std::time::Duration;

    use tempfile::TempDir;

    use super::*;

    /// Creates an executable fake EDS in an isolated workspace.
    fn fake_eds(script_body: &str) -> TempDir {
        let workspace = tempfile::tempdir().unwrap();
        let executable = workspace.path().join("eds");
        std::fs::write(&executable, format!("#!/bin/sh\n{script_body}\n")).unwrap();
        let mut permissions = std::fs::metadata(&executable).unwrap().permissions();
        permissions.set_mode(0o755);
        std::fs::set_permissions(executable, permissions).unwrap();
        workspace
    }

    /// Returns a simulator configured for a temporary fake EDS workspace.
    fn simulator(workspace: &TempDir) -> SedaroSimulator {
        SedaroSimulator::new(&PathBuf::from(workspace.path()))
    }

    /// Verifies that a fixed seed generates the same case seeds and values.
    #[test]
    fn monte_carlo_sampling_is_reproducible() {
        let target = EdsPatchTarget::new("agent", "engine", "mass", "f64");
        let parameter = MonteCarloParameter::new(
            "mass",
            target,
            ProbabilityDistribution::Normal {
                mean: 100.0,
                std_dev: 2.0,
            },
        );
        let path = PathBuf::from("unused");
        let first = MonteCarloStudy::new(SedaroSimulator::new(&path), 1.0)
            .samples(4)
            .seed(42)
            .parameter(parameter.clone())
            .generate_cases()
            .unwrap();
        let second = MonteCarloStudy::new(SedaroSimulator::new(&path), 1.0)
            .samples(4)
            .seed(42)
            .parameter(parameter)
            .generate_cases()
            .unwrap();

        let first_values: Vec<_> = first
            .iter()
            .map(|case| (case.seed, case.parameters["mass"]))
            .collect();
        let second_values: Vec<_> = second
            .iter()
            .map(|case| (case.seed, case.parameters["mass"]))
            .collect();
        assert_eq!(first_values, second_values);
    }

    /// Verifies that ambiguous duplicate parameter names are rejected.
    #[test]
    fn monte_carlo_rejects_duplicate_parameters() {
        let target = EdsPatchTarget::new("agent", "engine", "mass", "f64");
        let parameter = MonteCarloParameter::new(
            "mass",
            target,
            ProbabilityDistribution::Uniform {
                low: 1.0,
                high: 2.0,
            },
        );
        let study = MonteCarloStudy::new(SedaroSimulator::new(&PathBuf::from("unused")), 1.0)
            .samples(1)
            .parameter(parameter.clone())
            .parameter(parameter);

        assert!(
            study
                .generate_cases()
                .unwrap_err()
                .to_string()
                .contains("duplicate Monte Carlo parameter")
        );
    }

    /// Verifies that invalid probability distributions fail before execution.
    #[test]
    fn monte_carlo_rejects_invalid_distributions() {
        let study = MonteCarloStudy::new(SedaroSimulator::new(&PathBuf::from("unused")), 1.0)
            .samples(1)
            .parameter(MonteCarloParameter::new(
                "mass",
                EdsPatchTarget::new("agent", "engine", "mass", "f64"),
                ProbabilityDistribution::Normal {
                    mean: 1.0,
                    std_dev: 0.0,
                },
            ));

        assert!(study.generate_cases().is_err());
    }

    /// Verifies deterministic ordering and preservation of unsuccessful EDS output.
    #[tokio::test]
    async fn trade_study_preserves_case_order_and_failures() {
        let workspace = fake_eds("case \"$*\" in *bad*) exit 7 ;; *) exit 0 ;; esac");
        let target = EdsPatchTarget::new("agent", "engine", "value", "f64");
        let study = TradeStudy::new(simulator(&workspace), 1.0)
            .case(StudyCase::new("good").patch(target.patch(1.0)))
            .case(StudyCase::new("bad").patch(target.patch("bad")));

        let result = study.run().await.unwrap();

        assert_eq!(result.termination, StudyTermination::Completed);
        assert_eq!(result.runs[0].case.id, "good");
        assert_eq!(result.runs[1].case.id, "bad");
        assert!(result.runs[0].succeeded());
        assert!(!result.runs[1].succeeded());
        assert_eq!(result.successful_runs().count(), 1);
        assert_eq!(result.failed_runs().count(), 1);
    }

    /// Verifies that infrastructure failures are recorded without stopping later cases.
    #[tokio::test]
    async fn trade_study_continues_after_launch_failures() {
        let workspace = fake_eds("exit 0");
        std::fs::remove_file(workspace.path().join("eds")).unwrap();
        let study = TradeStudy::new(simulator(&workspace), 1.0)
            .case(StudyCase::new("first"))
            .case(StudyCase::new("second"));

        let result = study.run().await.unwrap();

        assert_eq!(result.runs.len(), 2);
        assert_eq!(result.failed_runs().count(), 2);
        assert!(matches!(result.runs[0].outcome, StudyRunOutcome::Failed(_)));
    }

    /// Verifies that an explicit executable path is used rather than a literal `./eds` path.
    #[tokio::test]
    async fn simulator_accepts_an_executable_path() {
        let workspace = fake_eds("exit 0");
        let executable = workspace.path().join("eds");
        let result = SedaroSimulator::new(&executable)
            .run_collect(1.0)
            .await
            .unwrap();

        assert!(result.success);
    }

    /// Verifies that EDS receives an owned target config and that it is cleaned up.
    #[tokio::test]
    async fn simulator_uses_and_cleans_unique_target_config() {
        let workspace = fake_eds(
            "printf '%s\\n' \"$*\" >> invocations && for arg in \"$@\"; do if [ \"$previous\" = \"--target-config\" ]; then mkdir -p \"$arg\"; fi; previous=\"$arg\"; done",
        );
        let first = simulator(&workspace);
        let second = first.clone();

        first.run_collect(1.0).await.unwrap();
        second.run_collect(1.0).await.unwrap();

        let invocations = std::fs::read_to_string(workspace.path().join("invocations")).unwrap();
        let target_configs: Vec<_> = invocations
            .lines()
            .map(|invocation| {
                let args: Vec<_> = invocation.split_whitespace().collect();
                let index = args
                    .iter()
                    .position(|arg| *arg == "--target-config")
                    .unwrap();
                args[index + 1]
            })
            .collect();

        assert_eq!(target_configs.len(), 2);
        assert_ne!(target_configs[0], target_configs[1]);
        for target_config in target_configs {
            assert_eq!(target_config.len(), 32);
            assert!(
                target_config
                    .chars()
                    .all(|character| character.is_ascii_hexdigit())
            );
            assert!(!workspace.path().join(target_config).exists());
        }
    }

    /// Verifies that malformed target output becomes a run failure instead of a panic.
    #[tokio::test]
    async fn malformed_target_output_is_a_run_failure() {
        let workspace = fake_eds(
            "for arg in \"$@\"; do if [ \"$previous\" = \"--target-config\" ]; then mkdir -p \"$arg\" && printf '%s\\n' '{\"data\":{\"config\":\"\",\"stream_id\":\"x\",\"type\":\"(\"},\"event\":\"config\",\"stream_id\":\"x\"}' > \"$arg/broken.jsonl\"; fi; previous=\"$arg\"; done",
        );
        let study = TradeStudy::new(simulator(&workspace), 1.0).case(StudyCase::new("broken"));

        let result = study.run().await.unwrap();

        assert!(matches!(result.runs[0].outcome, StudyRunOutcome::Failed(_)));
    }

    /// Verifies that cancellation drops the child process and preserves partial-study metadata.
    #[tokio::test]
    async fn cancellation_stops_the_active_process_and_returns_partial_results() {
        let workspace = fake_eds("exec sleep 30");
        let study = TradeStudy::new(simulator(&workspace), 1.0)
            .case(StudyCase::new("slow"))
            .case(StudyCase::new("never-started"));
        let cancellation = CancellationToken::new();
        let cancel_from_task = cancellation.clone();
        tokio::spawn(async move {
            tokio::time::sleep(Duration::from_millis(50)).await;
            cancel_from_task.cancel();
        });

        let result = tokio::time::timeout(
            Duration::from_secs(2),
            study.run_with_cancellation(&cancellation),
        )
        .await
        .expect("cancellation should terminate the child promptly")
        .unwrap();

        assert_eq!(result.termination, StudyTermination::Cancelled);
        assert_eq!(result.runs.len(), 1);
        assert!(result.runs[0].cancelled());
        assert_eq!(result.remaining_runs(), 1);
    }
}
